name: recruitment-platform
services:
- name: backend
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/recruitment-platform
  health_check:
    http_path: /api/health
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: DB_HOST
    scope: RUN_TIME
    type: SECRET
  - key: DB_USER
    scope: RUN_TIME
    type: SECRET
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: DB_NAME
    scope: RUN_TIME
    type: SECRET
  - key: DB_PORT
    value: "3306"

- name: frontend
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/recruitment-platform
  build_command: cd client && npm install && npm run build
  output_dir: client/build
  envs:
  - key: REACT_APP_API_URL
    value: ${backend.url}/api 